name: Kustomize diff

on:
  workflow_dispatch:

jobs:
  kustomize-diff:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: Kustomize Diff on PR
        uses: amazingandyyy/kustomize-diff@v1.0.3
        with:
          files: |
            kustomization/base/kustomization.yaml
            kustomization/cluster/**/kustomization.yaml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
