name: Kustomize diff

on:
  push:
    branches: [main] # just for testing
  workflow_dispatch:

jobs:
  diff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: kustomize diff
        id: kustomize-diff
        uses: amazingandyyy/kustomize-diff@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
