name: Kustomize diff

on:
  workflow_dispatch:

jobs:
  kustomize-diff:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: Kustomize Diff on PR
        uses: amazingandyyy/kustomize-diff@gha-v1.0.1
        with:
          message: hello world
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
